### GET request get all categories
GET {{URL}}/categories
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vMTI3LjAuMC4xOjgwMDAvYXBpL3JlZnJlc2gtdG9rZW4iLCJpYXQiOjE3NTg3NDkxNjUsImV4cCI6MTc1ODc1Mjk4OSwibmJmIjoxNzU4NzQ5Mzg5LCJqdGkiOiJ0aDViR05WWlNHNFVkZnRoIiwic3ViIjoiMzQ3IiwicHJ2IjoiMjNiZDVjODk0OWY2MDBhZGIzOWU3MDFjNDAwODcyZGI3YTU5NzZmNyJ9.tqq0afOCzA99vFq8OWaQnq8x91uhzrAiEFb8cR07k4c
###
