### GET request to search categories by name
GET {{url}}/categories/search/s5
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vMTI3LjAuMC4xOjgwMDAvYXBpL3YxL2xvZ2luIiwiaWF0IjoxNzU5OTI1NjMyLCJleHAiOjE3NTk5MjkyMzIsIm5iZiI6MTc1OTkyNTYzMiwianRpIjoiQWl3ckdQcVpCalpjbDA0SyIsInN1YiI6IjQwOSIsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjcifQ.aIKds3VggROjvb95k4eLaKwVE46cP_hqxNPG9j4AB1o
###
