### POST request to force delete by token
POST {{url}}/force-delete-user
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vMTI3LjAuMC4xOjgwMDAvYXBpL3YxL2xvZ2luIiwiaWF0IjoxNzU4MzcyOTMyLCJleHAiOjE3NTgzNzY1MzIsIm5iZiI6MTc1ODM3MjkzMiwianRpIjoiVURKem12NE9nZjZaOUZFUiIsInN1YiI6IjMzMyIsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjcifQ.hWQwHobYRPW0AF0imLo7TtNs5OmtJ6W_3KkjeMcETzw
###
