### GET request to get authenticated user
GET http://127.0.0.1:8000/api/user
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vMTI3LjAuMC4xOjgwMDAvYXBpL3YxL3JlZ2lzdGVyIiwiaWF0IjoxNzU4OTM1ODA2LCJleHAiOjE3NTg5Mzk0MDYsIm5iZiI6MTc1ODkzNTgwNiwianRpIjoiR0NxTlg2WXJseENBbklvZiIsInN1YiI6IjM1MSIsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjcifQ.2lTdtA1i8zn9_8f2eDQ4foqEzvgjb01nxibtxmRDdbE
###

