### GET request to get authenticated user
GET http://127.0.0.1:8000/api/user
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vMTI3LjAuMC4xOjgwMDAvYXBpL3YxL2xvZ2luIiwiaWF0IjoxNzU3OTE2ODYxLCJleHAiOjE3NTc5MjA0NjEsIm5iZiI6MTc1NzkxNjg2MSwianRpIjoiS3hIQ1YyelVTU05Pb0NOMSIsInN1YiI6IjMyMSIsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjcifQ.eavIixMid9xWt01lTlMzVogoYhYlYb1WilXuMPc2sGI
###

