### GET request to check if email is verified
GET {{url}}/auth/is-verified
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vMTI3LjAuMC4xOjgwMDAvYXBpL3YxL3JlZ2lzdGVyIiwiaWF0IjoxNzU5MzU4NDAyLCJleHAiOjE3NTkzNjIwMDIsIm5iZiI6MTc1OTM1ODQwMiwianRpIjoibEgyYTNURWdFSlpZQ3h0WSIsInN1YiI6IjM4NyIsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjcifQ.XX0bALVvf-A0Iq85a2OePgYt2DEBoYcLj2gKcfbTc7o
###
