### POST request to logout user
POST {{url}}/logout
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vMTI3LjAuMC4xOjgwMDAvYXBpL3YxL2xvZ2luIiwiaWF0IjoxNzYwMTc3MzE3LCJleHAiOjE3NjAxODA5MTcsIm5iZiI6MTc2MDE3NzMxNywianRpIjoiM2xKdUdlVnQ1WmRxcXcwbCIsInN1YiI6IjQwOSIsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjcifQ.15q4BzijlW8AvCVj1cqLjfC5XPtYicXih5huCeDz6kY
Accept: application/json
Content-Type: application/json
