### GET request to example server
POST {{url}}/refresh-token
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vMTI3LjAuMC4xOjgwMDAvYXBpL3YxL3JlZ2lzdGVyIiwiaWF0IjoxNzU4NzQ5MTY1LCJleHAiOjE3NTg3NTI3NjUsIm5iZiI6MTc1ODc0OTE2NSwianRpIjoielF6YnZjWmtzR0FOcmZrMSIsInN1YiI6IjM0NyIsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjcifQ.ezy4WXfUwjcgB85yaZmr3kELARNGCnTAbCYn9I1PC0U
Accept: application/json
Content-Type: application/json
###
