### GET request to register new user
POST {{url}}/v1/register
Accept: application/json
Content-Type: application/json

{
    "email": "mai-ali@gamil.com",
    "password": "44611697Qq*",
    "password_confirmation": "44611697Qq*",
    "name": "Mai Ali",
    "username": "mai-ali",
    "role": "student",
    "phone": "01277672244",
    "bio": "Hello, I'm Mai from EGYPT."
}
###
#    "avatar": ""D:\Laravel_Storm\public\myImage.png""
