### GET request to register new user
POST {{url}}/v1/register
Accept: application/json
Content-Type: application/json

{
    "email": "youssef.ahmed.dev01@gmail.com",
    "password": "44611697Qq*",
    "password_confirmation": "44611697Qq*",
    "name": "youssef ahmed",
    "username": "youssef.ahmed.dev01",
    "role": "admin",
    "phone": "+201290493875",
    "bio": "Hello, I'm youssef.ahmed.dev01 Ahmed from EGYPT cairo."
}
###
