### GET request to example server
POST {{url}}/auth/resend-verification
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vMTI3LjAuMC4xOjgwMDAvYXBpL3YxL3JlZ2lzdGVyIiwiaWF0IjoxNzU5MjgzMjY2LCJleHAiOjE3NTkyODY4NjYsIm5iZiI6MTc1OTI4MzI2NiwianRpIjoiT1U1dGcxUEV2RGVxVGVocyIsInN1YiI6IjM2NSIsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjcifQ.1UfwxWAPKB1Byw_bpZbE-JBBo0WPJOcnERxOyTmP3ZA

{
    "email": "youssef.ahmed.fci@gmail.com"
}

###
