### GET request to reset password by otp
POST {{url}}/v1/reset-password-by-otp
Accept: application/json
Content-Type: application/json

{
    "email": "youssef.ahmed.fci@gmail.com",
    "two_factor_code": "6645",
    "password": "A419386Yy=***",
    "password_confirmation": "A419386Yy=***"
}

###
