### POST request to create a new profile
POST {{url}}/profiles
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vMTI3LjAuMC4xOjgwMDAvYXBpL3YxL2xvZ2luIiwiaWF0IjoxNzU3ODIxMDcyLCJleHAiOjE3NTc4MjQ2NzIsIm5iZiI6MTc1NzgyMTA3MiwianRpIjoiUDI2cFJ0ODlHbHNEbG00ZCIsInN1YiI6IjMyMSIsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjcifQ.2eIBQ_h8FIhkfS7f_tvhEMYwbwscUN_xrG9PomWtC-Y

{
    "age": 25,
    "bio": "Software developer with a passion for open source.",
    "address": "Cairo, Egypt",
    "user_id": 321
}
###
