### GET request to show profile by ID
GET {{url}}/profiles/1
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vMTI3LjAuMC4xOjgwMDAvYXBpL3YxL2xvZ2luIiwiaWF0IjoxNzU3ODIxNTI2LCJleHAiOjE3NTc4MjUxMjYsIm5iZiI6MTc1NzgyMTUyNiwianRpIjoiQXNiQlN3STh0N3M3U292TyIsInN1YiI6IjMyMSIsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjcifQ.-H_ghMamL1yMU_2Ky6YDK8d8oLqB1__oFbzBp4wZa_o
###
