### GET request to fetch all notifications related to the authenticated user
GET {{url}}/notifications
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vMTI3LjAuMC4xOjgwMDAvYXBpL3YxL3JlZ2lzdGVyIiwiaWF0IjoxNzU4MDYzNzY4LCJleHAiOjE3NTgwNjczNjgsIm5iZiI6MTc1ODA2Mzc2OCwianRpIjoiTHVRUTN0UzBrcHNCUTlRWSIsInN1YiI6IjMzMSIsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjcifQ.J8kbLLMEgkp8rbKLyJAUF1tZLSWLhgNAigapJh68bHM
###
