### POST request to create new coures
POST {{URL}}/courses
Accept: application/json
Content-Type: application/json
Authorization: Bearer 10|nSu2sMK8sTju9zVaEFNkBPLR1c0GoQbg3z5RuBRMcfd45419

{
    "title": "C++",
    "description": "cpp lang low level",
    "instructor_id": 3,
    "level": "beginner",
    "price": 89.65,
    "category_id": 2,
    "duration": 120,
    "status":"archived"
}
###
