### GET request to get authenticated user
GET http://127.0.0.1:8000/api/user
Content-Type: application/json
Accept: application/json
Authorization: Bearer 13|XmylAfKVxrnPLaDZgCRZ9PlOPeEltVD8Rv2ZaDRH2d1c2ac9
###

