### GET request to register new user
POST {{url}}/v1/register
Accept: application/json
Content-Type: application/json

{
    "email": "vovo120@gamil.com",
    "password": "44611697Q",
    "password_confirmation": "44611697Q",
    "name": "Youssef A Mohsen",
    "username": "Novo012",
    "role": "admin",
    "phone": "010250151770",
    "bio": "Hello, I'm Youssef A Mohsen"
}
###
