### GET request to example server
POST {{URL}}/register
Accept: application/json
Content-Type: application/json

{
    "email": "admin9687@outlook.com",
    "password": "44611697",
    "password_confirmation": "44611697",
    "name": "Youssef",
    "username": "admin9687",
    "role": "admin",
    "phone": "01020781897"
}
###
