### GET request to register new user
POST {{URL}}/v1/register
Accept: application/json
Content-Type: application/json

{
    "email": "jow544445@gmail.com",
    "password": "44611697",
    "password_confirmation": "44611697",
    "name": "Youssef A Mohsen",
    "username": "jow544445",
    "role": "student",
    "phone": "015354354564"
}
###
