### POST request to create a new user
POST {{url}}/v1/register
Accept: application/json
Content-Type: application/json

{
    "email": "ttoo@gmail.com",
    "password": "44611697",
    "password_confirmation": "44611697",
    "name": "Ali",
    "username": "tooStD",
    "role": "student",
    "phone": "353518057994",
    "bio": "I am an stu1 user.sd sdf adf adf  asdf asd fd af f qwr eq we ew qr wre er q er e"
}
###
