### POST request to create a new user
POST {{url}}/v1/register
Accept: application/json
Content-Type: application/json

{
    "email": "ttooi@gmail.com",
    "password": "44611697tYt-",
    "password_confirmation": "44611697tYt-",
    "name": "ttooi",
    "username": "ttooi",
    "role": "instructor",
    "phone": "353578057994",
    "bio": "I am a new instructor here to teach amazing courses!"
}
###
