### GET request to example server
PATCH {{url}}/users/142
Accept: application/json
Content-Type: application/json
Authorization: Bearer Qr372QbeeLug4iEJ1JjeTrRNxtgzpEKlGKRcR3IMe156d772

{
    "name": "Updated Name"
}
###
