### POST request for creating a review
POST http://127.0.0.1:8000/api/reviews
Accept: application/json
Content-Type: application/json
Authorization: Bearer 1|5a4RVQnq2ZYI7FogodFuB3eeXKyjGzEnmpPqqkL669d01d3d

{
    "course_id": 2,
    "user_id": 1,
    "rating": 5,
    "comment": "Great course!"
}
