### POST request to create a new user
POST {{url}}/v1/register
Accept: application/json
Content-Type: application/json

{
    "email": "egypt@dev.com",
    "password": "44611697tYt-",
    "password_confirmation": "44611697tYt-",
    "name": "ttooi",
    "username": "egypt00",
    "role": "instructor",
    "phone": "153578057994",
    "bio": "I am a new instructor here to teach amazing courses!",
    "avatar": "Youssef_Ahmed.jpg"
}
###
