### GET request to get all instructors
GET {{url}}/users/instructors
Accept: application/json
Content-Type: application/json
Authorization: Bearer 18|hYu7GJmDLg0RdOlQ003AfZ4Ios97h742NCNX7jzLa8e21ea5
###
