### POST request to create new coures
POST {{url}}/courses
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vMTI3LjAuMC4xOjgwMDAvYXBpL3YxL2xvZ2luIiwiaWF0IjoxNzU5MDEyODcwLCJleHAiOjE3NTkwMTY0NzAsIm5iZiI6MTc1OTAxMjg3MCwianRpIjoiR3NvQVAzRWREa3o4Zjd3VSIsInN1YiI6IjM1MyIsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjcifQ.ASnPoeP7h4upwtIn58FTCudlnHhe1NFvi0lgaX9b7pA

{
    "title": "Go v7",
    "description": "Learn new JAVA from scratch to advanced",
    "instructor_id": 9,
    "level": "beginner",
    "price": 10000,
    "category_id": 2,
    "duration": 120,
    "status": "archived",
    "thumbnail": "https://example.com/thumbnail.jpg"
}

###
