### POST request to create a new user
POST {{url}}/register
Accept: application/json
Content-Type: application/json

{
    "email": "admi1@gmail.com",
    "password": "44611697",
    "password_confirmation": "44611697",
    "name": "admin user1",
    "username": "student12",
    "role": "admin",
    "phone": "353515957964",
    "bio": "I am an stu1 user.sd sdf adf adf  asdf asd fd af f qwr eq we ew qr wre er q er e"
}
###
