### POST request to create a new user
POST {{url}}/register
Accept: application/json
Content-Type: application/json

{
    "email": "stu1@gmail.com",
    "password": "44611697",
    "password_confirmation": "44611697",
    "name": "stu user1",
    "username": "student1",
    "role": "student",
    "phone": "3535159579",
    "bio": "I am an stu1 user."
}
###
