### GET request to search user by username
GET {{url}}/users/search/wglover
Content-Type: application/json
Authorization: Bearer 16|cL44vEDdpfB5law29TzonegIvCivZblbwSKwHzCvc1bcba14
Accept: application/json

###
